### ISSUE TITLE
amount sent in namereg txs is not always correct.

### ISSUE THREAD

**Issue by androlo** [eris-ltd/eris-db.js#12]
The token cost for storing a string of data a given number of turns using  `NameReg.setEntry` is not always correct.

**Comment by androlo** [comment]
(The amount it sends to the server is the correct amount according to the formula in js, but this does not translate to the expected number blocks, so the formula probably doesn't match the one in Tendermint).

**Comment by NodeGuy** [comment]
Would you please write a failing test or give me an example?

**Comment by androlo** [comment]
Did not see it the last time I tried. Been lots of changes to both eris-db and Tendermint.
