### ISSUE TITLE
Solved! 

### ISSUE THREAD

**Issue by BeyondLimitation** [eris-ltd/eris-db.js#13]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'test' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose config Skipping project config: /home/lee/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT, open '/home/lee/package.json'
5 verbose stack     at Error (native)
6 verbose cwd /home/lee
7 error Linux 3.16.0-40-generic
8 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "test"
9 error node v0.12.7
10 error npm  v2.11.3
11 error path /home/lee/package.json
12 error code ENOENT
13 error errno -2
14 error enoent ENOENT, open '/home/lee/package.json'
14 error enoent This is most likely not a problem with npm itself
14 error enoent and is related to npm not being able to find a file.
15 verbose exit [ -2, true ]
=================================================
How to solve this problem?

**Comment by dennismckinnon** [comment]
Hello beyond limitations. I am going to need to see the command you tried to type in. One thing that is important is its 'eris-db' not erisdb.

**Comment by BeyondLimitation** [comment]
@dennismckinnon Hi, Thanks for answer! But i solved it!

**Comment by compleatang** [comment]
Good to hear!
