### ISSUE TITLE
Websocket hooks

### ISSUE THREAD

**Issue by androlo** [eris-ltd/eris-db.js#14]
Add for closed and perhaps others. If someone want to use it they can just create a ws client and pass that to edb using the `createInstanceFromClient` method. Probably something like this: 

```
var wsClient = new edbModule.clients.WebSocketClient(someURL);
wsClient.addSocketClosedCallback(callbackFn));
var edb = edbModule.createInstanceFromClient(wsClient);
```
`eris-contracts` has an option to pass in an edb instance to the pipes (so no changes needed).

**Comment by dennismckinnon** [comment]
Wondering about the expected time you will implement this? I know you have a lot going on right now so maybe best if I implement a hacky work-around for the time being?

**Comment by androlo** [comment]
This week for sure.

**Comment by NodeGuy** [comment]
Dennis, would you please explain how this would be valuable to you?

**Comment by dennismckinnon** [comment]
I think it might already be implemented But I was planning on using it to re-establish a connection to an edb instance if the websocket got closed.

**Comment by androlo** [comment]
This is done.
