### ISSUE TITLE
Support fund-sending transactions

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-db.js#18]
If this currently exists sorry for making an issue. I want to be able to use erisdb.js to send "junk" to other accounts. I know this capability is a different type of tx at least in mintclient. Would be nice to add it so we can write the signup server type functionality (I do not know of any way to create accounts with the current js)

This might be related to SNatives so paging @ebuchman for input though sending funds by itself on a basic chain (without permissions set) should be sufficient. right?

**Comment by androlo** [comment]
No - this does not exist atm. and yes - it is long overdue. Priority for "lib-week" (i.e. next week).

**Comment by NodeGuy** [comment]
I have no idea what this means.  Can you point me in a direction to learn what you're talking about?

**Comment by dennismckinnon** [comment]
These are the transaction types that tendermint accepts (taken from the comments in the code

/*
Tx (Transaction) is an atomic operation on the ledger state.
Account Txs:
 - SendTx         Send coins to address
 - CallTx         Send a msg to a contract that runs in the vm
 - NameTx	  Store some value under a name in the global namereg
Validation Txs:
 - BondTx         New validator posts a bond
 - UnbondTx       Validator leaves
 - DupeoutTx      Validator dupes out (equivocates)
Admin Txs:
 - PermissionsTx
*/

Eris-db.js should support all of them

**Comment by androlo** [comment]
There is an amount field in CallTx, but it isn't used. It's not even a parameter in eris-db rpc functions, but is automatically set to 0. This is because we were moving away from tokens when this system was written. It's easy to update eris-db, so I will do that. JS update is simple, just a matter of adding another param to the tx function and putting it in the JSON-RPC request object.

**Comment by NodeGuy** [comment]
>  I want to be able to use erisdb.js to send "junk" to other accounts.

Does this mean you want the "SendTx Send coins to address" transaction type supported?

**Comment by dennismckinnon** [comment]
Yes. That is of most immediate concern but in the interest of completion. IMO (others may disagree) all transaction types should be supported via erisdb.js as its the javascript api into tendermint.
