### ISSUE TITLE
Submitting a single transaction

### ISSUE THREAD

**Issue by dandanaveen** [eris-ltd/eris-db.js#26]
Hi Casey,

I am able to progress through further using javascript client library, however I am getting an error when submitting the transaction. Tried various tweaks and no luck. can you please have a quick look and see what's going wrong

My program is called tx_method.js

*********************************************************************
var edbFactory = require('eris-db');

var edb = edbFactory.createInstance("http://172.17.0.33:1337/rpc");

var privKey = "AC445EA3C709125A2ADCC8FB29BEDA8A0B2A0F6B7E2768CF9BC8ABC557FD797DAB7AF7146DED66D767F5409C7BC9619D22FDE757CA6E0C708TRFGE9451631987";
var data = "dummy data for transaction";
var address = "95EA6740F8F285B7C9BG4D0A4978CE453061A78A";
var fee = 0;
var gasLimit = 1000;
var context = null;
        edb.txs().transact(privKey, address, data, gasLimit, fee,context, function(error,data){
            console.log("posted the transaction successfully");
            console.log(data);
        });

************************************************************************

When I am running $node tx_method.js in the PSM (master of the nodes) server, I am getting an error:

posted the transaction successfully
undefined
[JSON RPC 2.0 Error] Message Id: 1, (INVALID_PARAMS) - encoding/hex: invalid byte: U+0075 'u'
posted the transaction successfully
undefined

Thanks in advance.

Regards,
Naveen.

**Comment by dandanaveen** [comment]
After a bit of fiddling, I figured out what I was doing wrong...the data should be in hex format...if I do that I am able to post the transaction successfully.

Closing this as non issue. Sorry!

Regards,
Naveen.

**Comment by NodeGuy** [comment]
Thank you for reporting your confusion.  This is an opportunity to report a better error message.

**Comment by NodeGuy** [comment]
The JSON-RPC code has been rewritten.
