### ISSUE TITLE
GET calls not key dependent

### ISSUE THREAD

**Issue by slowtokyo** [eris-ltd/eris-db.js#30]
You can read data out of the chain without keys. Posting (transacting) data on the chain however requires keys.

You guys are probably already aware (and I think this is part of the upcoming keys update?) so feel free to close this if so.

**Comment by NodeGuy** [comment]
Yes, I am aware but thank you for pointing it out.  This is tracked by https://github.com/eris-ltd/eris-contracts.js/issues/23.
