### ISSUE TITLE
getBlocks does not include blockmeta object

### ISSUE THREAD

**Issue by rguikers** [eris-ltd/eris-db.js#32]
When using the getBlock RPC call we never receive the meta object in the response.
Would be nice to receive multiple blocks at once when implementing block explorer functionality..

seems that the blockmeta object is always empty in the response. The documentation states different.

**Comment by NodeGuy** [comment]
I hear your desire to receive the meta object and I'm curious about your assertion about the documentation.  [The documentation I'm looking at](https://github.com/eris-ltd/eris-db/blob/master/api.md#return-value-10) shows the following structure in the response:

```
{

    header: {
        chain_id:        <string>
        height:          <number>
        time:            <string>
        fees:            <number>
        num_txs:         <number>
        last_block_hash: <string>
        last_block_parts: {
            total: <number>
            hash:  <string>
        }
        state_hash: <string>
    }
    validation: {
        commits: [<Commit>]
        TODO those other two.
    }
    data: {
        txs: [<Tx>]
        TODO that other field.
    }
}
```

I don't see any mention of the meta object.  Am I missing something?

**Comment by NodeGuy** [comment]
This is a bug in Eris DB: https://github.com/eris-ltd/eris-db/issues/120
