### ISSUE TITLE
Transact and hold turns handled errors into crashes

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-db.js#33]
As promised, see this line of code:

https://github.com/eris-ltd/eris-db.js/blob/master/lib/unsafe.js#L116

when any sort of error gets returned from erisdb the data field is not set so data2[1] results in can find field '1' of undefined causing lots of nasty crashes even for things like timeouts.

The fix is simple:

if (data2) {data2 = data2[1];}

**Comment by NodeGuy** [comment]
Fixed.
