### ISSUE TITLE
NPM update of eris-db

### ISSUE THREAD

**Issue by rguikers** [eris-ltd/eris-db.js#34]
Hi, I see that the npm is not updated to the latest version. 
"npm install eris-db" will result in an outdated version for now.

**Comment by NodeGuy** [comment]
NPM [does have the latest version](https://www.npmjs.com/package/eris-db), which is `0.15.0`.  You can see it is the most recent in [the list of releases](https://github.com/eris-ltd/eris-db.js/releases) on GitHub.

**Comment by rguikers** [comment]
Hi David,

In that case the documentation does not really help from the site. Mainly looking for the setpermission function. Is there a timeframe for releasing this?

Thanks,

**Comment by NodeGuy** [comment]
Are you referring to this documentation?

https://docs.erisindustries.com/documentation/eris-db.js/

No, there isn't a timeframe for the next release.  I would like to have timeframes for releases and am working toward achieving this.

**Comment by rguikers** [comment]
Thanks David,

No was referring to the master branch docs.. Sorry to be a bit impatient :)
Just looking for easy implementation of onboarding system for now. No worries, hope it gets into a version soon..

**Comment by NodeGuy** [comment]
Sorry for the confusion.  After the next release I'll make sure that `master` is always coinciding with a release.
