### ISSUE TITLE
genPrivAccount does not get broadcast - eris-db.js

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-db.js#36]
This is a mirror of @Fukunaga42 issue raised in eris-db: https://github.com/eris-ltd/eris-db/issues/227,
which should be raised here, but can be interesting to track on e-db and e-db.js

**Comment by NodeGuy** [comment]
Closing this issue because eris-db.js is simply calling Eris DB's `genPrivAccount`.  Any confusion or wanted change in behavior is on the Eris DB side.
