### ISSUE TITLE
Address passed with 0x Prefix cause "invalid address" errors [BETA BRANCH]

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-db.js#40]
The issue occurs when transactions or calls are made and the "to" address (address the transaction is being sent to) string is prefaced with "0x" (which seems to be how they are being returned from contract calls now) When an address provided is prefaced by 0x then 
https://github.com/eris-ltd/eris-db.js/blob/beta/lib/transactions.js#L82 fails and same with transactandhold etc.

I don't know if sending it with the "0x" prefix to erisdb would cause a problem @benjaminbollen  might be able to comment on that. If no problems there then my recommendation would be that we adapt the util.isAddress() function to allow for optional 0x prefacing. If it is a problem though then we should have some sanitization going on at the lowest common point to remove the 0x if present automatically.

**Comment by dennismckinnon** [comment]
I am patching this at the eris-contracts level for the internal project currently being worked on

**Comment by benjaminbollen** [comment]
it's a bit unexpected that the client library has moved forward on the hex representation before the server has.  E-db to my knowledge (and quickly asserted) that eris-db does not support `0x` prefixing of hex strings at this point (or has)

**Comment by dennismckinnon** [comment]
Its my belief (though unconfirmed) that moving to web3 has introduced addresses with 0x prefixed hex strings and that when these strings are fed back into transactions (an example being the address of an accountManager contract being retrieved from DOUG and then being used to access the account manager) it causes a (if what you are saying about edb not supporting 0x prefixing is correct) a correct error.

In which case it should continue to error if the final transactions are containing to addresses with 0x but somewhere before that the lib should auto remove the 0x from address strings if present. (It would be a nightmare to ensure that any returned argument from a call is cleaned first before used elsewhere especially in this case where the 0x doesn't make it wrong... just not as right)

**Comment by NodeGuy** [comment]
This is probably a result of my partially-unforking web3 in eris-contracts.js.  Would you please give me an example of how I can recreate an address being returned from a contract call and being prefixed with `0x`?

**Comment by NodeGuy** [comment]
0.15.3 no longer returns addresses prefixed with `0x`.
