### ISSUE TITLE
read-only mode for pipes

### ISSUE THREAD

**Issue by androlo** [eris-ltd/eris-db.js#5]
from @dennismckinnon 

make it so that the pipe use read-only mode if a tx-signer/key/whatever is not added. it'll allow calls and events, but transact would put an error in the callback saying there is no way of validating. 

different pipes would use different errors, but base pipe class gets a generic 'setIdData' function (actual name TBD) that can be used to set the needed data, which would put it in normal read/write mode.

aside from the typical read-only property there is an especially important use-case for this, and that is when the (encrypted) identification data is kept on-chain.

**Comment by dennismckinnon** [comment]
Also allow for tx-signer/key/whatever to be added after the fact? (upgrade from read-only to read-write)

**Comment by androlo** [comment]
yes, that 'setIDData' would be used for that (or whatever it'll be called). i can make it so that the simple creation functions would automatically create read-only pipes if the id func/key/etc. is omitted. like the createDev function now that takes url and private key would just start the DevPipe in read only and wait for a key to be added.

**Comment by androlo** [comment]
(if the key param is omitted, otherwise go directly to read/write mode)

**Comment by androlo** [comment]
contracts issue. will be added in next minor v.
