### ISSUE TITLE
Support an eris-db cluster running behind a load balancer

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-db.js#56]
**Problem** -- Currently eris-db.js does not (by default) handle load balanced environments well. When running the below setup there are frequent (but intermittent) errors. These are likely due to the polling nature of eris-db's base networking stack; each poll the loadbalancer sees as a new connection and routes it to a different eris-db.js node which has not registered the event subscription. After that eris-db throws, and eris-db.js never gets the information.

```
multiple eris-db's -> load balancer -> node middleware running eris-db.js
```

The effect here is that users need to remove the load balancer which has sub-optimal results in high volume environments. 

I have no idea what the solution is here, but I cannot imagine we're the first that has had to solve the fundamental problem at hand of event pub-sub through a load balancer.

**Comment by NodeGuy** [comment]
This is an architectural problem in Eris DB, not eris-db.js.  You can try working around it by setting `service.spec.sessionAffinity` to `ClientIP` in Kubernetes.

**Comment by compleatang** [comment]
Do you mean the string `ClientIP` or that's to be filled in with the appropriate variable? (Am assuming the latter but want to check).

**Comment by NodeGuy** [comment]
The string `"ClientIP"`.

**Comment by compleatang** [comment]
Great! Works well.
