### ISSUE TITLE
one-time websocket events can't find callback for weird extra event

### ISSUE THREAD

**Issue by androlo** [eris-ltd/eris-db.js#8]
Doesn't cause any bugs as far as I've been able to see, but I need to look into it. Probably getting some extra event (possibly a duplicate) because of how things are set up - which is ignored - but need to find out what's going on...

**Comment by NodeGuy** [comment]
Do you have a failing test?

**Comment by androlo** [comment]
No. It doesn't break anything. Will look into it later.
